name: x_gaussian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=13.0.2
  - plyfile=0.8.1
  - python=3.10
  - pip=22.3.1
  - numpy==1.24.1
  - tqdm
  - imageio
  - pyyaml
  - pip:
      - torch==2.9.0 -i https://mirrors.nju.edu.cn/pytorch/whl/cu130
      - torchvision==0.24.0 -i https://mirrors.nju.edu.cn/pytorch/whl/cu130
      - torchaudio==2.9.0 -i https://mirrors.nju.edu.cn/pytorch/whl/cu130
